/**
 * index.mjs — the EAGER half of the shipped item bank.
 *
 * GENERATED by content/items/build-index.mjs — do not hand-edit.
 *
 * NOTHING WITH A PER-ITEM OR PER-LOCALE COST IS IN HERE. What a page load pays for, in full: the
 * manifest (lessons and per-knowledge-point meta, no items), three loader tables, and one
 * eight-character fingerprint. Everything with a size is behind an `import()`:
 *
 *   groups/<kpId>.mjs        the items, one chunk per knowledge point, pulled per lesson.
 *   strings/items-<l>.mjs    the item text, one chunk per locale, one pulled per learner.
 *   spine.mjs                the identity spine, pulled only when the fingerprint basis moved.
 *
 * In NODE all of it is pulled eagerly at module init — `tools/bank-audit.mjs`,
 * `review/measure/P16.mjs`, `review/measure/P17.mjs` and four critic scripts read `BANK` and
 * `STRINGS` synchronously, there is no bandwidth to save offline, and a DELIVERY decision must not
 * change a single measured value. In the BROWSER both are `null` and neither chunk is requested:
 * `ItemBank` reaches the locale table through `STRING_LOADERS`, and nothing in the running game
 * reads the spine at all.
 *
 * `form` and `family` are slices of the id, which is `${family}/${form}/${hash}` by construction.
 */
export const LOCALES = ["en","es","pl"];

export { MANIFEST, LESSONS, KP_META } from "./manifest.mjs";
export { GROUP_IDS, GROUP_LOADERS } from "./groups/index.mjs";

import { MANIFEST as _M } from "./manifest.mjs";
/** The build-time index, kept under its round-1 name because P17's stats surface reads it. */
export const BANK_INDEX = _M;

/**
 * One static specifier per locale, for the same reason `groups/index.mjs` has one per knowledge
 * point: a computed specifier is either left alone by the bundler and 404s in production, or swept
 * into a glob that pulls all three languages back into one chunk.
 */
export const STRING_LOADERS = {
  "en": () => import("./strings/items-en.mjs"),
  "es": () => import("./strings/items-es.mjs"),
  "pl": () => import("./strings/items-pl.mjs"),
};

/** One locale's item text as `{ key: string }`. `null` for a locale we do not ship. */
export async function loadItemStrings(locale) {
  const loader = STRING_LOADERS[locale];
  if (!loader) return null;
  const mod = await loader();
  return mod.default ?? mod;
}

/**
 * `bankAuditFingerprint({ bankFiles: BANK, model })`, computed at BUILD time over the spine.
 *
 * `BANK_FINGERPRINT_BASIS` keys the audit constants that value was folded over — the Mastery audit
 * version and its sampling constants, plus the graph's identifiability caps.
 * `app/src/boot/62-learning.js` recomputes the key from the LIVE constants on every page load and
 * only trusts the scalar when the two agree, so a constant that changed without a rebuild falls
 * back to the spine instead of silently validating a stale price table.
 */
export const BANK_FINGERPRINT = "d6e2537d";
export const BANK_FINGERPRINT_BASIS = "e5a9c7e1";
export const BANK_AUDIT_VERSION_AT_BUILD = 2;

export function bankFingerprintBasis({ version, perCell, window, candidates, sampleCap, forms, caps }) {
  const parts = [
    "v" + version,
    perCell,
    window,
    candidates,
    sampleCap,
    (forms || []).join(","),
    ...Object.keys(caps || {}).sort().map((k) => k + "=" + caps[k]),
  ].join("|");
  let h = 0x811c9dc5;
  for (let i = 0; i < parts.length; i += 1) {
    h ^= parts.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return (h >>> 0).toString(16).padStart(8, "0");
}

/** Decode the spine. 1152 items, one pass, no allocation beyond the objects themselves. */
export function decodeSpine(spine) {
  return spine.split("\u0000").map((block) => {
    const lines = block.split("\n");
    const items = [];
    for (let i = 1; i < lines.length; i += 1) {
      const line = lines[i];
      const t1 = line.indexOf("\t");
      const t2 = line.indexOf("\t", t1 + 1);
      const id = line.slice(0, t1);
      const s1 = id.indexOf("/");
      const s2 = id.indexOf("/", s1 + 1);
      items.push({
        id,
        family: id.slice(0, s1),
        form: id.slice(s1 + 1, s2),
        difficulty: Number(line.slice(t1 + 1, t2)),
        answer: { canonical: line.slice(t2 + 1) },
      });
    }
    return { kpId: lines[0], items };
  });
}

/** The round-1 `BANK` shape, pulled on demand. The stale-audit branch is the only caller. */
export async function loadBankSpine() {
  const mod = await import("./spine.mjs");
  return decodeSpine(mod.SPINE ?? mod.default);
}

const IS_NODE =
  typeof process !== "undefined" && !!process.versions?.node && typeof window === "undefined";

/** Every locale of every key, `{ key: { en, es, pl } }` — the round-1 shape. NODE ONLY. */
async function assembleStrings() {
  const tables = await Promise.all(LOCALES.map((l) => loadItemStrings(l)));
  const out = {};
  LOCALES.forEach((locale, i) => {
    for (const [key, text] of Object.entries(tables[i])) (out[key] ??= {})[locale] = text;
  });
  return out;
}

export const BANK = IS_NODE ? await loadBankSpine() : null;
export const STRINGS = IS_NODE ? await assembleStrings() : null;
