/* GENERATED by content/items/build-index.mjs — do not hand-edit. */
export const GROUP_IDS = ["var-meaning","oo-numeric","expr-anatomy","oo-structure","eval-substitute","eval-signed","eval-formula","translate-phrase","translate-order","props-operations","like-terms-id","like-terms-combine","distribute-numeric","distribute-variable","distribute-negative","simplify-expression","equivalent-expressions","eq-meaning","props-equality","eq-one-add","eq-one-mult","eq-two-step","eq-combine-side","eq-distribute","eq-both-sides","eq-special-cases","translate-sentence","eq-model-context","ineq-meaning","ineq-one-step","ineq-negative-flip","ineq-two-step"];

/**
 * One static specifier per group, so the bundler emits one chunk per knowledge point. A computed
 * specifier — `import(`./${kpId}.mjs`)` — would either be left alone by the bundler (and 404 in
 * production) or swept into a glob that pulls the whole catalogue back into one chunk.
 */
export const GROUP_LOADERS = {
  "var-meaning": () => import("./var-meaning.mjs"),
  "oo-numeric": () => import("./oo-numeric.mjs"),
  "expr-anatomy": () => import("./expr-anatomy.mjs"),
  "oo-structure": () => import("./oo-structure.mjs"),
  "eval-substitute": () => import("./eval-substitute.mjs"),
  "eval-signed": () => import("./eval-signed.mjs"),
  "eval-formula": () => import("./eval-formula.mjs"),
  "translate-phrase": () => import("./translate-phrase.mjs"),
  "translate-order": () => import("./translate-order.mjs"),
  "props-operations": () => import("./props-operations.mjs"),
  "like-terms-id": () => import("./like-terms-id.mjs"),
  "like-terms-combine": () => import("./like-terms-combine.mjs"),
  "distribute-numeric": () => import("./distribute-numeric.mjs"),
  "distribute-variable": () => import("./distribute-variable.mjs"),
  "distribute-negative": () => import("./distribute-negative.mjs"),
  "simplify-expression": () => import("./simplify-expression.mjs"),
  "equivalent-expressions": () => import("./equivalent-expressions.mjs"),
  "eq-meaning": () => import("./eq-meaning.mjs"),
  "props-equality": () => import("./props-equality.mjs"),
  "eq-one-add": () => import("./eq-one-add.mjs"),
  "eq-one-mult": () => import("./eq-one-mult.mjs"),
  "eq-two-step": () => import("./eq-two-step.mjs"),
  "eq-combine-side": () => import("./eq-combine-side.mjs"),
  "eq-distribute": () => import("./eq-distribute.mjs"),
  "eq-both-sides": () => import("./eq-both-sides.mjs"),
  "eq-special-cases": () => import("./eq-special-cases.mjs"),
  "translate-sentence": () => import("./translate-sentence.mjs"),
  "eq-model-context": () => import("./eq-model-context.mjs"),
  "ineq-meaning": () => import("./ineq-meaning.mjs"),
  "ineq-one-step": () => import("./ineq-one-step.mjs"),
  "ineq-negative-flip": () => import("./ineq-negative-flip.mjs"),
  "ineq-two-step": () => import("./ineq-two-step.mjs"),
};
