import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const { Graph } = await import(`file://${ROOT}/app/src/learn/Graph.js`);
const { Mastery } = await import(`file://${ROOT}/app/src/learn/Mastery.js`);
const GRAPH = new Graph(JSON.parse(fs.readFileSync(path.join(ROOT, "content/knowledge-graph.json"), "utf8")));
const table = JSON.parse(fs.readFileSync(path.join(ROOT, "app/src/learn/bank-audit.json"), "utf8"));
const m = new Mastery(GRAPH, { bankAudit: table, storage: null, emit: () => {} });
const d = m.cellPricing.description;
console.log("cellsPriced", d.cellsPriced, "catalogueShare", d.catalogueShare);
console.log("rejected groups:", d.rejectedCells.length);
console.log("repriced cells:", d.repricedCells.length);
console.log("unmasterable:", JSON.stringify(d.unmasterable));
console.log("relaxed:", JSON.stringify(d.relaxed));
console.log("\nissues:");
for (const i of m.issues) console.log("  - " + i);
console.log("\nrefusals (worst first):");
for (const r of d.rejectedCells.slice(0, 45)) console.log(`  ${r.cell}${r.family ? "::" + r.family : ""}  ${r.reason}  ${JSON.stringify(r.modalAnswer ?? null)}`);
console.log("\nre-priced:");
for (const r of d.repricedCells) console.log(`  ${r.cell}  ${r.from} -> ${r.to}`);
const scored = [];
for (const kp of GRAPH.ids) for (const f of ["construct", "repair", "generate"]) if (m.isScorable(kp, f, "solo")) scored.push(`${kp}|${f}`);
console.log(`\nscored cells: ${scored.length} of 96`);
